[customizations.fdo]
manufacturing_server_url = ""
diun_pub_key_insecure = "true"

[customizations.installer.kickstart]
contents = """
lang en_GB.UTF-8
keyboard uk
timezone CET

text --non-interactive
zerombr
clearpart --all --initlabel
autopart --type=lvm

# user setup
user --name redhat --password password --plaintext --groups wheel
rootpw --lock
# network configuration
network --bootproto=dhcp --device=link --activate --onboot=on
reboot --eject

%post --log=/var/log/anaconda/post-install.log --erroronfail
export MANUFACTURING_SERVER_URL="http://manufacturing.sandbox2519.opentlc.com"
export DIUN_PUB_KEY_INSECURE="true"

# For DNS resolution
echo "nameserver 192.168.1.1" > /etc/resolv.conf

/usr/libexec/fdo/fdo-manufacturing-client
%end
"""